name: "Deploy prueba"

on:
  push:
    branches: ["main"]
    
jobs:
  deploy-prueba:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Publicar versiones"
      - run: echo "Publicar version master"
