name: Deploy to server test

on: push

jobs:
    firts_job:
        runs-on: ubuntu-latest

        env:
            NAME: PruebaENV

        steps:
            - name: Hola mundo
              run: echo "Hola mundo $NAME"
            
    second_job:
        if: ${{ github.ref == 'refs/heads/master' }}
        needs: firts_job
        runs-on: ubuntu-latest

        steps:
            - name: Hola mundo
              run: echo "Hola mundo ${{github.ref}}"