name: Deploy to server test

on: push

jobs:
    firts_job:
        name: Test utilizando Action
        runs-on: ubuntu-latest

        outputs:
            salida: ${{ steps.step_1.outputs.my_variable }}

        env:
            NAME: PruebaENV

        steps:
            - name: Working dir
              run: ls -al

            - name: Action
              uses: actions/checkout@v4

            - name: Working dir after action
              run: ls -al

            - name: Dir of git file
              run: echo $GITHUB_OUTPUT

            - name: Save variable in git file
              id: step_1
              run: echo "my_variable=Hola mundo" >> $GITHUB_OUTPUT

            - name: Get message variable
              run: echo "${{ steps.step_1.outputs.my_variable }}"
            
    second_job:
        if: ${{ github.ref == 'refs/heads/master' }}
        needs: firts_job
        runs-on: ubuntu-latest

        env:
            SALIDA: ${{ needs.firts_job.outputs.salida }}

        steps:
            - name: Hola mundo
              run: echo "Hola mundo ${{github.ref}}"

            - name: Variable salida entre jobs
              run: echo "$salida"