name: Deploy to server test

on: push

jobs:
    firts_job:
        name: Test utilizando Action
        runs-on: ubuntu-latest

        env:
            NAME: PruebaENV

        steps:
            - name: Working dir
              run: ls -al

            - name: Action
              uses: actions/checkout@v4

            - name: Working dir after action
              run: ls -al

            - name: Variable git
              run: echo $GITHUB_OUTPUT
            
    second_job:
        if: ${{ github.ref == 'refs/heads/master' }}
        needs: firts_job
        runs-on: ubuntu-latest

        steps:
            - name: Hola mundo
              run: echo "Hola mundo ${{github.ref}}"